- .gitignore
- test.sh
> Sandbox: step2

- Makefile
- include/minishell.h
- src/interpret.c
- src/main.c
- test.sh
- `interpret()`関数の作成. 
- 絶対PATHで渡したコマンドの実行. 
- `minishell.h`の作成. 
- `main()`の中で入力があれば`interpret()`に渡す. 
- 入力が2words以上のときの処理. 
- 相対PATHやコマンド名のみを渡したときの実行.
> Sandbox: step3

- Makefile
- include/prototype.h
- include/struct.h
- src/exec/interpret.c
- src/expand/expand.c
- src/main.c
- src/parse/parse.c
- `parse()`の作成. 
- `t_node`構造体の作成. 
- `main.c`内で使用する`expand()`と`interpret()`の引数を`t_node *`に対応. 
- `parse()`のエラー処理.
> Sandbox: step7

- Makefile
- include/prototype.h
- src/builtin/builtin.c
- src/builtin/builtin_unset.c
- builtin関数の`unset`の作成. 
- `unset`の簡単なテスト
```shell
(examples)
minishell$ export ARG2=yeah
minishell$ unset ARG2
minishell$ export ARG2=yeah
minishell$ unset ARG2 ARG3
minishell$ export ARG=yeah ARG2=yeahyeah
minishell$ unset ARG2 ARG3 ARG4
```
- test.shの更新. 
- norm対応. 
Closes #13
> [Step14] finish unset 

- Makefile
- include/macro.h
- include/prototype.h
- src/builtin/builtin.c
- src/builtin/builtin_cd.c
- src/exec/search_path.c
- builtin関数の`cd`の作成. 
- `cd`の簡単なテスト
```shell
minishell$ cd
minishell$ pwd
> /home/yotsubo
----------
minishell$ cd ./
minishell$ pwd
> /home/yotsubo/42/mini-shell
----------
minishell$ cd ../mini-shell/./../mini-shell/.././fdf/
minishell$ pwd
> /home/yotsubo/42/fdf
```
- test.shの更新. 
- norm対応. 
Closes #15
> [step14] finish cd

- Makefile
- include/minishell.h
- include/prototype.h
- src/builtin/builtin.c
- src/builtin/builtin_pwd.c
- builtin関数の`pwd`の作成. 
- `pwd`の簡単なテスト
```shell
minishell$ pwd
> /home/yotsubo/42/mini-shell
----------
minishell$ unset PWD
minishell$ pwd
> /home/yotsubo/42/mini-shell
```
- test.shの更新. 
- norm対応. 
- `PATH_MAX`の調査
Closes #17
> [step14] finish pwd

- .gitignore
- test.sh
- 全体テストの拡充
inf_loop中のシグナル対応
Closes #26
> [TEST] 26:expand test

- test.sh
- review 項目に合わせた test の拡充
- 詳細なテスト
close #65
> 65 add review check list to test

- include/struct.h
- src/builtin/builtin.c
- src/env/env.c
- src/env/hashmap.c
- src/exec/interpret.c
- src/expand/expand_variable.c
- src/expand/remove_quote.c
- src/test/env_test.c
- src/tokenize/tokenize.c
- exportの何かを再現した気がするけどWord Splittingで記憶がないです. 
- shellの深さを表す環境変数の調整. 
- exportの際の環境変数_の出力.
- **Word Splitting**
close #44
> 44 fix export

- test.sh
- env NGのコメントアウト（NGで良いため）
- それに付随するコメントの追加
- なし
close #46
> [#46] add: env test discription for NG's. don't have to be OK

- Makefile
- include/prototype.h
- src/exec/interpret.c
- src/redirect/heredoc.c
- src/redirect/redirect.c
- src/xlib/xdup.c
- test.sh
- stashfd を用いたredirect outputの修正
- xdupの作成
- norm
#37
> 37 redirecting output

- .gitignore
- include/prototype.h
- src/builtin/builtin_cd.c
- src/env/env.c
- src/env/hashmap.c
- `$PWD`, `$OLDPWD`の微調整.
- `echo`が2引数以上に対応していないのでNGのまま
- ビルトインとパイプを組み合わせたときに自作のビルトインを使ってくれない.
- norm
↓前
```shell
[pwd]                                                                 :  diff OK  status OK
[cd\npwd]                                                             :  diff NG  status NG, expected 0 but got 1
[cd src\npwd]                                                         :  diff NG  status NG, expected 0 but got 1
[cd /etc\npwd]                                                        :  diff NG  status NG, expected 0 but got 1
[cd . \n pwd \n echo $PWD $OLDPWD]                                    :  diff NG  status OK
[cd .. \n pwd \n echo $PWD $OLDPWD]                                   :  diff NG  status OK
[cd /// \n pwd \n echo $PWD $OLDPWD] …
```
> 49 fix pwd

- test.sh
- word splitting 範囲のテスト削除
- 
#97
> [#97] done: word splitting tests

- test.sh
- テストケースの追加.
※今までのissue消化で達成されていたので, ソースコードの変更はありません.
- ソースコードの変更.
#87
> 87 fix env empty string key

- src/getset/getset.c
- `getset`ディレクトリのnorm対応. 
- 特になし. 
- `norminette ./getset`によるnorm errorの有無
#124
> [#124] ref: getset.c: adjust to norm

- src/destruct/free_map.c
- `destruct`ディレクトリのnorm対応. 
- 特になし. 
- `norminette ./src/destruct`によるnorm errorの有無
#119
> 119 norm destruct 

- src/signal/signal.c
- `signal`ディレクトリのnorm対応. 
- 特になし. 
- `norminette ./src/signal`によるnorm errorの有無
#127
> 127 norm signal

- include/prototype.h
- src/expand/expand_heardoc.c
- src/expand/expand_variable.c
- src/expand/remove_quote.c
- src/expand/special_parameter.c
- `expand`ディレクトリのnorm対応. 
- 特になし. 
- `norminette ./src/expand`によるnorm errorの有無
#123
> 123 norm expand

- src/error/error.c
- src/error/syntax_error.c
- `error`ディレクトリのnorm対応. 
- 特になし. 
- `norminette ./src/error`によるnorm errorの有無
#121
> 121 norm error

- src/exec/token_list_to_argv.c
- 中途半端にやったタスクのせいで入ってたゴミを無視した.
- `test.sh`での確認.
- 本当に消してよかったものなのかの入念なチェック.
#150
> 150 fix env var include space

- include/macro.h
- src/exec/exec.c
- src/main.c
- src/redirect/heredoc.c
- src/signal/signal.c
- heredoc 中に Ctr-D (EOF) が送られたときの終了ステータスを0に変更
- heredoc 中に Ctr-D (EOF) が送られたときのwarningを修正
- execの返り値をpid_tにrefactor
- 特になし
#91
> [#91] mod: heredoc c-D(EOF) last status to 0
